package pty

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime/debug"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/creack/pty/v2"
	"github.com/sirupsen/logrus"
)

// Frame types for the daemon wire protocol.
const (
	FrameOutput      = 0x01 // daemon → client: raw PTY output
	FrameInput       = 0x02 // client → daemon: raw bytes to write to PTY
	FrameResize      = 0x03 // client → daemon: 4 bytes (cols u16 BE + rows u16 BE)
	FrameClose       = 0x04 // client → daemon: kill shell
	FrameReplay      = 0x05 // daemon → client: ring buffer contents on connect
	FrameQueryBuffer = 0x06 // client → daemon: request ring buffer replay (0 payload)
)

// DaemonConfig configures a session daemon.
type DaemonConfig struct {
	ID          string // unique session identifier
	Shell       string // shell to spawn (default: $SHELL or /bin/bash)
	Cols, Rows  uint16 // initial terminal size
	Cwd         string // working directory
	SocketDir   string // directory for Unix sockets (default: /tmp/termyard-sessions-{uid}/)
	SystemdUnit string // systemd scope unit name for cleanup (empty if not using systemd)
	BufferSize  int    // ring buffer size in bytes (default: 8MB)
	Nonce       string // 8-byte hex random for instance identity (generated by server)
}

// RunDaemon is the entry point for a session daemon process.
// It creates a PTY, spawns the shell, listens on a Unix socket,
// and serves clients until the shell exits or Close is received.
// sessionMeta is written as a JSON sidecar file alongside the socket.
type sessionMeta struct {
	ID            string `json:"id"`
	Pid           int    `json:"pid"`
	ShellPid      int    `json:"shell_pid"`
	Shell         string `json:"shell"`
	Cwd           string `json:"cwd"`
	Created       string `json:"created"`
	Cols          uint16 `json:"cols"`
	Rows          uint16 `json:"rows"`
	SystemdUnit   string `json:"systemd_unit,omitempty"`
	Nonce         string `json:"nonce,omitempty"`           // 8-byte hex from server; empty for legacy
	ProcStartTime int64  `json:"proc_start_time,omitempty"` // /proc/<pid>/stat field 22 for legacy fallback
}

func RunDaemon(cfg DaemonConfig) error {
	// Ensure we're a session leader so we survive parent/server restarts.
	// Registry.Create sets Setsid on the child, but if someone starts us
	// directly (e.g. systemd, manual invocation) we need our own session.
	syscall.Setsid() // no-op if already a session leader
	signal.Ignore(syscall.SIGHUP)

	if cfg.Shell == "" {
		cfg.Shell = os.Getenv("SHELL")
		if cfg.Shell == "" {
			cfg.Shell = "/bin/bash"
		}
	}
	if cfg.SocketDir == "" {
		cfg.SocketDir = fmt.Sprintf("/tmp/termyard-sessions-%d", os.Getuid())
	}
	if cfg.BufferSize <= 0 {
		cfg.BufferSize = 8 << 20 // 8 MB
	}

	log := logrus.WithFields(logrus.Fields{
		"id":    cfg.ID,
		"shell": cfg.Shell,
		"cols":  cfg.Cols,
		"rows":  cfg.Rows,
	})

	// 1. Create PTY + spawn shell.
	//
	// When Shell is a bare interactive shell binary (bash/zsh/etc.), run it
	// directly. Otherwise treat it as a command to run inside the user's default
	// shell. The command is injected into the PTY after startup so the shell
	// stays alive after the command exits (user lands at a shell prompt).
	// This also handles commands with arguments like "pi -c" which exec.Command
	// cannot spawn directly (it would look for a binary named "pi -c").
	var cmd *exec.Cmd
	var initCommand string // non-empty → inject into PTY after shell starts
	if isInteractiveShell(cfg.Shell) {
		cmd = exec.Command(cfg.Shell)
	} else {
		defaultShell := os.Getenv("SHELL")
		if defaultShell == "" {
			defaultShell = "/bin/bash"
		}
		cmd = exec.Command(defaultShell)
		initCommand = cfg.Shell
	}
	cmd.Env = directLocaleEnv()
	cmd.Env = append(cmd.Env, "TERM=xterm-256color")
	cmd.Env = append(cmd.Env, "TERMYARD_SESSION="+cfg.ID)
	cmd.Env = append(cmd.Env, "TERMYARD_PANE="+cfg.ID+":0.0")
	if cfg.Cwd != "" {
		cmd.Dir = cfg.Cwd
	}

	ptyFd, err := pty.StartWithSize(cmd, &pty.Winsize{
		Cols: cfg.Cols,
		Rows: cfg.Rows,
	})
	if err != nil {
		return fmt.Errorf("start PTY: %w", err)
	}
	log.Info("started session daemon PTY")

	// If a non-shell command was requested, inject it into the PTY now.
	// The shell buffers the input and executes it once it shows its first
	// prompt. A short delay lets the shell finish its rc-file sourcing so
	// PATH and environment are fully set up before the command runs.
	if initCommand != "" {
		go func() {
			time.Sleep(150 * time.Millisecond)
			_, _ = ptyFd.Write([]byte(initCommand + "\n"))
		}()
	}

	// 2. Ring buffer.
	ring := newRingBuffer(cfg.BufferSize)

	// 3. Listen on Unix socket.
	socketPath := filepath.Join(cfg.SocketDir, cfg.ID+".sock")
	metadataPath := filepath.Join(cfg.SocketDir, cfg.ID+".json")
	if err := os.MkdirAll(cfg.SocketDir, 0700); err != nil {
		ptyFd.Close()
		cmd.Process.Kill()
		return fmt.Errorf("create socket dir: %w", err)
	}

	// Check whether a live daemon is already bound to this socket.
	// If we can connect to it, refuse to start — we must not steal an
	// active session.  If the socket file exists but nobody is listening,
	// it is a stale leftover and we can safely remove it.
	if isDaemonAlive(socketPath) {
		ptyFd.Close()
		killProcessGroup(cmd.Process.Pid)
		return fmt.Errorf("session %q is already active (socket %s is live)", cfg.ID, socketPath)
	}
	os.Remove(socketPath)   // remove stale socket
	os.Remove(metadataPath) // remove stale metadata

	ln, err := net.Listen("unix", socketPath)
	if err != nil {
		ptyFd.Close()
		killProcessGroup(cmd.Process.Pid)
		return fmt.Errorf("listen on %s: %w", socketPath, err)
	}
	defer os.Remove(socketPath)
	defer os.Remove(metadataPath)

	// Write metadata sidecar so Registry.List can discover sessions.
	daemonPid := os.Getpid()
	meta := sessionMeta{
		ID:            cfg.ID,
		Pid:           daemonPid,
		ShellPid:      cmd.Process.Pid,
		Shell:         cfg.Shell,
		Cwd:           cfg.Cwd,
		Created:       time.Now().Format(time.RFC3339),
		Cols:          cfg.Cols,
		Rows:          cfg.Rows,
		SystemdUnit:   cfg.SystemdUnit,
		Nonce:         cfg.Nonce,
		ProcStartTime: procStartTime(daemonPid),
	}
	metaBytes, _ := json.Marshal(meta)
	if err := os.WriteFile(metadataPath, metaBytes, 0600); err != nil {
		ptyFd.Close()
		killProcessGroup(cmd.Process.Pid)
		ln.Close()
		return fmt.Errorf("write metadata: %w", err)
	}

	log.WithField("socket", socketPath).Info("daemon listening")

	// 4. Build and run the daemon.
	d := &daemon{
		config:     cfg,
		ptyFd:      ptyFd,
		cmd:        cmd,
		ring:       ring,
		ln:         ln,
		socketPath: socketPath,
		log:        log,
		clients:    make(map[net.Conn]chan []byte),
		shellDone:  make(chan struct{}),
	}

	// Handle SIGTERM from `systemctl --user stop <scope>` (KillMode=
	// control-group sends SIGTERM to the whole cgroup). Without this the
	// daemon ignores it and gets SIGKILLed after the 90s stop timeout,
	// leaving a lingering `failed` scope. shutdown() is idempotent.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGTERM)
	go func() {
		<-sigCh
		log.Debug("received SIGTERM, shutting down")
		d.shutdown()
	}()

	return d.run()
}

// ringBuffer is a simple circular byte buffer.
type ringBuffer struct {
	buf  []byte
	head int // next write position
	tail int // oldest read position
	size int // number of valid bytes
	mu   sync.Mutex
}

func newRingBuffer(capacity int) *ringBuffer {
	return &ringBuffer{buf: make([]byte, capacity)}
}

// Write appends data to the ring buffer, overwriting oldest data if full.
// Uses at most two slice copies instead of per-byte modulo.
func (r *ringBuffer) Write(data []byte) {
	r.mu.Lock()
	defer r.mu.Unlock()

	if len(data) == 0 {
		return
	}

	n := len(r.buf)
	if n == 0 {
		return
	}

	m := len(data)
	if m > n {
		data = data[m-n:]
		m = n
	}

	// Number of free bytes before we must overwrite.
	free := n - r.size
	// How much of the write is new capacity vs overwrite.
	used := min(m, free)
	over := m - used

	// (a) Fill any remaining capacity first.
	if used > 0 {
		dest := r.head
		availToEnd := n - dest
		if used <= availToEnd {
			copy(r.buf[dest:], data[:used])
			dest += used
		} else {
			copy(r.buf[dest:], data[:availToEnd])
			copy(r.buf[0:], data[availToEnd:used])
			dest = used - availToEnd
		}
		if dest >= n {
			dest -= n
		}
		r.head = dest
		r.size += used
	}

	if over <= 0 {
		return
	}

	// (b) Overwrite the oldest region. The per-byte loop advances both head
	// and tail together, so after overwriting m bytes the new tail equals the
	// new head.
	data = data[used:]
	dest := r.head
	availToEnd := n - dest
	if over <= availToEnd {
		copy(r.buf[dest:], data)
		dest += over
	} else {
		copy(r.buf[dest:], data[:availToEnd])
		copy(r.buf[0:], data[availToEnd:])
		dest = over - availToEnd
	}
	if dest >= n {
		dest -= n
	}
	r.head = dest
	r.tail = dest
}

// Snapshot returns a copy of all buffered bytes in order (oldest first).
// Uses at most two copies instead of per-byte modulo.
func (r *ringBuffer) Snapshot() []byte {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.size == 0 {
		return nil
	}
	if r.size == len(r.buf) {
		// Full buffer: [tail..end] + [0..head].
		first := len(r.buf) - r.tail
		out := make([]byte, len(r.buf))
		copy(out, r.buf[r.tail:])
		copy(out[first:], r.buf[:r.head])
		return out
	}
	// Partial buffer is always contiguous from tail.
	out := make([]byte, r.size)
	copy(out, r.buf[r.tail:r.tail+r.size])
	return out
}

// SnapshotTail returns the trailing maxBytes of the buffer in chronological
// order (oldest first among the tail). Uses at most two copies.
func (r *ringBuffer) SnapshotTail(maxBytes int) []byte {
	r.mu.Lock()
	defer r.mu.Unlock()

	if r.size == 0 {
		return nil
	}
	if maxBytes <= 0 {
		return nil
	}

	if r.size <= maxBytes {
		if r.size == len(r.buf) {
			// Full buffer: [tail..end] + [0..head].
			first := len(r.buf) - r.tail
			out := make([]byte, len(r.buf))
			copy(out, r.buf[r.tail:])
			copy(out[first:], r.buf[:r.head])
			return out
		}
		out := make([]byte, r.size)
		copy(out, r.buf[r.tail:r.tail+r.size])
		return out
	}

	// Return only the last maxBytes. Logical index i maps to
	// physical buf[(tail+i)%n].
	n := len(r.buf)
	out := make([]byte, maxBytes)
	start := r.size - maxBytes
	startIdx := (r.tail + start) % n
	first := n - startIdx
	if first >= maxBytes {
		copy(out, r.buf[startIdx:startIdx+maxBytes])
	} else {
		copy(out, r.buf[startIdx:])
		copy(out[first:], r.buf[:maxBytes-first])
	}
	return out
}

// daemon manages the PTY, ring buffer, and client fan-out.
type daemon struct {
	config     DaemonConfig
	ptyFd      *os.File
	cmd        *exec.Cmd
	ring       *ringBuffer
	ln         net.Listener
	socketPath string
	log        *logrus.Entry

	clientsMu sync.RWMutex
	clients   map[net.Conn]chan []byte // per-client write channel

	shellDone chan struct{}
	closeOnce sync.Once
}

func (d *daemon) run() error {
	defer func() {
		if r := recover(); r != nil {
			d.log.WithFields(logrus.Fields{
				"panic": r,
				"stack": string(debug.Stack()),
			}).Error("daemon run accept loop panicked")
		}
	}()

	// Goroutine: read PTY → ring buffer → broadcast.
	go d.pumpPTY()

	// Goroutine: wait for shell exit.
	go d.waitShell()

	// Accept loop.
	for {
		conn, err := d.ln.Accept()
		if err != nil {
			select {
			case <-d.shellDone:
				return nil
			default:
				return fmt.Errorf("accept: %w", err)
			}
		}
		go d.handleClient(conn)
	}
}

// pumpPTY reads from the PTY and fans out output to all clients.
func (d *daemon) pumpPTY() {
	defer func() {
		if r := recover(); r != nil {
			d.log.WithFields(logrus.Fields{
				"panic": r,
				"stack": string(debug.Stack()),
			}).Error("daemon pumpPTY panicked — shutting down")
			d.shutdown()
		}
	}()

	buf := make([]byte, 64*1024)
	for {
		n, err := d.ptyFd.Read(buf)
		if n > 0 {
			data := make([]byte, n)
			copy(data, buf[:n])
			d.ring.Write(data)
			d.broadcast(data)
		}
		if err != nil {
			if err != io.EOF {
				d.log.WithError(err).Debug("PTY read error")
			}
			d.shutdown()
			return
		}
	}
}

// waitShell waits for the shell process to exit, then shuts down.
func (d *daemon) waitShell() {
	_ = d.cmd.Wait()
	d.log.Debug("shell process exited")
	d.shutdown()
}

// broadcast sends an Output frame to all connected clients.
// Uses per-client goroutines with buffered channels so a slow client
// never blocks the PTY pump.
func (d *daemon) broadcast(data []byte) {
	frame := encodeFrame(FrameOutput, data)

	d.clientsMu.RLock()
	defer d.clientsMu.RUnlock()

	for _, ch := range d.clients {
		select {
		case ch <- frame:
		default:
			// Client is too slow; drop this frame.
		}
	}
}

// handleClient serves a single client connection.
func (d *daemon) handleClient(conn net.Conn) {
	defer func() {
		if r := recover(); r != nil {
			d.log.WithFields(logrus.Fields{
				"panic": r,
				"stack": string(debug.Stack()),
			}).Error("daemon handleClient panicked — closing connection")
			conn.Close()
		}
	}()

	d.log.Debug("client connected")

	writeCh := make(chan []byte, 256)
	d.addClient(conn, writeCh)
	defer func() {
		d.removeClient(conn)
		conn.Close()
		d.log.Debug("client disconnected")
	}()

	// Start writer goroutine (reads from writeCh, writes to conn).
	writerDone := make(chan struct{})
	go func() {
		defer close(writerDone)
		for data := range writeCh {
			if _, err := conn.Write(data); err != nil {
				return
			}
		}
	}()

	// 1. Send replay on connect.
	replay := d.ring.Snapshot()
	if len(replay) > 0 {
		frame := encodeFrame(FrameReplay, replay)
		select {
		case writeCh <- frame:
		default:
			// Client write buffer full on connect; disconnect.
			return
		}
	}

	// 2. Read frames from client.
	header := make([]byte, 5)
	for {
		if _, err := io.ReadFull(conn, header); err != nil {
			return
		}
		ftype := header[0]
		plen := binary.BigEndian.Uint32(header[1:5])

		if plen > 10*1024*1024 { // sanity: max 10 MiB per frame
			return
		}

		var payload []byte
		if plen > 0 {
			payload = make([]byte, plen)
			if _, err := io.ReadFull(conn, payload); err != nil {
				return
			}
		}

		switch ftype {
		case FrameInput:
			d.ptyFd.Write(payload)
		case FrameResize:
			if len(payload) == 4 {
				cols := binary.BigEndian.Uint16(payload[0:2])
				rows := binary.BigEndian.Uint16(payload[2:4])
				_ = pty.Setsize(d.ptyFd, &pty.Winsize{Cols: cols, Rows: rows})
			}
		case FrameQueryBuffer:
			// Send current ring buffer contents. A 4-byte big-endian uint32
			// payload requests at most that many trailing bytes; an empty
			// payload requests the full snapshot. New clients always receive
			// a FrameReplay, including an empty one, so they never have to
			// wait for a reply that will never come.
			var replay []byte
			if len(payload) == 4 {
				maxBytes := int(binary.BigEndian.Uint32(payload))
				replay = d.ring.SnapshotTail(maxBytes)
			} else {
				replay = d.ring.Snapshot()
			}
			frame := encodeFrame(FrameReplay, replay)
			select {
			case writeCh <- frame:
			default:
			}
		case FrameClose:
			d.shutdown()
			return
		}
	}
}

func (d *daemon) addClient(conn net.Conn, ch chan []byte) {
	d.clientsMu.Lock()
	d.clients[conn] = ch
	d.clientsMu.Unlock()
}

func (d *daemon) removeClient(conn net.Conn) {
	d.clientsMu.Lock()
	if ch, ok := d.clients[conn]; ok {
		delete(d.clients, conn)
		close(ch)
	}
	d.clientsMu.Unlock()
}

// closeAllClients closes all attached client connections and their write channels.
// This is called during shutdown to wake handleClient goroutines blocked in io.ReadFull.
func (d *daemon) closeAllClients() {
	d.clientsMu.Lock()
	defer d.clientsMu.Unlock()
	for conn, ch := range d.clients {
		conn.Close()
		close(ch)
	}
	d.clients = make(map[net.Conn]chan []byte)
}

// shutdown closes the PTY, kills the shell, and closes the listener.
// All attached client connections are closed to ensure handleClient
// goroutines exit promptly, which lets the daemon process exit and the
// server's watch connection observe EOF.
func (d *daemon) shutdown() {
	d.closeOnce.Do(func() {
		d.ptyFd.Close()
		// Kill the shell's entire process group so child processes
		// (background jobs, pipelines, etc.) are not leaked as orphans.
		// The shell is a session leader (pty.StartWithSize uses Setsid),
		// so its PID equals its process group ID.  Negative PID targets
		// the process group.  If the shell already exited this is a no-op.
		killProcessGroup(d.cmd.Process.Pid)
		d.ln.Close()
		// Close all attached client connections. This causes io.ReadFull in
		// handleClient to return with EOF, allowing those goroutines to exit
		// and the daemon process to terminate.
		d.closeAllClients()
		close(d.shellDone)
		d.log.Debug("daemon shutdown complete")
	})
}

// encodeFrame builds a wire-protocol frame.
func encodeFrame(ftype byte, payload []byte) []byte {
	frame := make([]byte, 5+len(payload))
	frame[0] = ftype
	binary.BigEndian.PutUint32(frame[1:5], uint32(len(payload)))
	copy(frame[5:], payload)
	return frame
}

// isDaemonAlive returns true if a daemon is currently listening on socketPath.
// Used by RunDaemon to avoid stealing a live daemon's socket.
func isDaemonAlive(socketPath string) bool {
	conn, err := net.DialTimeout("unix", socketPath, 500*time.Millisecond)
	if err != nil {
		return false
	}
	conn.Close()
	return true
}

// isInteractiveShell returns true when name is a bare shell binary (no spaces,
// no arguments) that should be spawned directly as the session shell.
// Any other value — a command with arguments or a non-shell binary — should be
// wrapped inside a shell so the session outlives the command.
var knownShells = map[string]bool{
	"bash": true, "zsh": true, "sh": true, "fish": true,
	"dash": true, "tcsh": true, "csh": true, "ksh": true,
	"mksh": true, "pdksh": true,
}

func isInteractiveShell(name string) bool {
	if strings.ContainsAny(name, " \t") {
		return false // has arguments — not a bare shell
	}
	return knownShells[filepath.Base(name)]
}

// killProcessGroup sends SIGKILL to the process group identified by pgid.
// If the process group no longer exists (e.g. shell already exited),
// this is silently ignored.
func killProcessGroup(pgid int) {
	if pgid <= 0 {
		return
	}
	// Negative PID sends the signal to the entire process group.
	_ = syscall.Kill(-pgid, syscall.SIGKILL)
}
